// class Autogenerated {
//   bool? success;
//   int? statusCode;
//   String? message;
//   List<Data>? data;
//
//   Autogenerated({this.success, this.statusCode, this.message, this.data});
//
//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     success = json['success'];
//     statusCode = json['statusCode'];
//     message = json['message'];
//     if (json['data'] != null) {
//       data = <Data>[];
//       json['data'].forEach((v) {
//         data!.add(new Data.fromJson(v));
//       });
//     }
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['success'] = this.success;
//     data['statusCode'] = this.statusCode;
//     data['message'] = this.message;
//     if (this.data != null) {
//       data['data'] = this.data!.map((v) => v.toJson()).toList();
//     }
//     return data;
//   }
// }
//
// class Data {
//   int? orderId;
//   int? driverId;
//   int? pointId;
//   List<Items>? items;
//
//   Data({this.orderId, this.driverId, this.pointId, this.items});
//
//   Data.fromJson(Map<String, dynamic> json) {
//     orderId = json['order_id'];
//     driverId = json['driver_id'];
//     pointId = json['point_id'];
//     if (json['items'] != null) {
//       items = <Items>[];
//       json['items'].forEach((v) {
//         items!.add(new Items.fromJson(v));
//       });
//     }
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['order_id'] = this.orderId;
//     data['driver_id'] = this.driverId;
//     data['point_id'] = this.pointId;
//     if (this.items != null) {
//       data['items'] = this.items!.map((v) => v.toJson()).toList();
//     }
//     return data;
//   }
// }
//
// class Items {
//   String? code;
//   int? status;
//
//   Items({this.code, this.status});
//
//   Items.fromJson(Map<String, dynamic> json) {
//     code = json['code'];
//     status = json['status'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['code'] = this.code;
//     data['status'] = this.status;
//     return data;
//   }
// }